/**
 * Event Names to be sent to Google Tag Manager
 */

export const GTMEventName = {
    FILTER_CLICK: "FILTER_CLICK",
    FILTER_SELECT: "FILTER_SELECT",
    FILTER_UNSELECT: "FILTER_UNSELECT",
    FILTER_NAME: "FILTER_NAME",
    FILTER_SEARCH: "FILTER_SEARCH",
    FILTER_SEARCH_TERM: "FILTER_SEARCH_TERM",
    STUDY_CLICK: "STUDY_CLICK",
    CONSORTIUM_SELECTION: "CONSORTIUM_SELECTION",
    TOOLTIP_HOVER: "TOOLTIP_HOVER",
    WORKSPACE_LIST_CLICK: "WORKSPACE_LIST_CLICK",
    TERRA_WORKSPACE_LINK_CLICK: "TERRA_WORKSPACE_LINK_CLICK",
    REQUEST_STUDY_ACCESS: "REQUEST_STUDY_ACCESS"
};