name: Run checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"
      
      - run: |
          cd packages/data-explorer-ui
          npm ci
          npm run check-format
          npm run lint
          npm run test
          npm run test-compile
